version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: developer
    command: start
    restart: on-failure
    volumes:
      - './:/usr/src/app'
    ports:
      - "3000:3000"
